baseURL = 'http://hugo.docker.amazee.io'
title = "jackwrfuller"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20


[markup.highlight]
style = "github-dark"

[params]
  author = "Jack W R Fuller"
  info = "Software Engineer"
  description = "Jack W R Fuller's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/kingcnut.jpg"
  #gravatar = "john.doe@example.com"
  commentoURL = "https://cdn.commento.io"

  faviconSVG = "/images/kingcnut-square.ico"

  footer = true
  credit = false


  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  customJS = ["js/temp-handler.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[params.umami]
  siteID = "498eafe9-df46-45a3-a240-6d66428ead82"
  scriptURL = "https://umami.main-umami.app.lagoon.jwrf.au/script.js"


# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/jackwrfuller/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://linkedin.com/in/jackwrfuller"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
