docker-compose-yaml: docker-compose.yml

routes:
  autogenerate:
    oauthProtected: true

environments:
  main:
    routes:
      - nginx:
        - jackwrfuller.au:
            tls-acme: 'true'
            insecure: Redirect
            oauthProtected: false
