docker-compose-yaml: docker-compose.yml

routes:
  autogenerate:
    oauthProtected: true

environments:
  o2p:
    routes:
      - nginx:
        - nginx.test.o2p.172.19.0.240.sslip.io:
            oauthProtected: true
        - nginx2.test.o2p.172.19.0.240.sslip.io:
            oauthProtected: true
        - nginx3.test.o2p.172.19.0.240.sslip.io:
            oauthProtected: false
        - nginx4.test.o2p.172.19.0.240.sslip.io:
